spring:
  application:
    name: pp-auth-admin
  thymeleaf:
    cache: false
    mode: HTML5
    check-template: true
    check-template-location: true
  datasource:
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      filters: stat
      max-active: 20
      url: jdbc:mysql://sontion.cn:3306/pp_auth?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=PRC&useSSL=false
      username: root
      password: rootabc,123
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
server:
  port: 8080
  servlet:
    context-path: /
  undertow:
    accesslog:
      enabled: true
      dir: /pp/logs/pp-auth-api
      pattern: common
mybatis:
  mapper-locations: classpath*:**/mapper/**/*Mapper.xml
jwt:
  secret: secret
  expiration: 7200000
  token: Authorization
