spring:
  datasource:
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      filters: stat
      max-active: 20
      url: jdbc:mysql://sontion.cn:3306/pp_auth?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=PRC&useSSL=false
      username: root
      password: rootabc,123
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
