spring:
  application:
    name: pp-test
  datasource:
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      max-active: 20
      url: jdbc:mysql://sontion.cn:3306/pp_auth?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=PRC&useSSL=false
      username: root
      password: rootabc,123
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
  quartz:
    job-store-type: jdbc
#    properties:
#      org:
#        quartz:
#          scheduler:
#            instanceId: AUTO
#            instanceName: pp_clusteredScheduler
#            skipUpdateCheck: true
#          jobStore:
#            class: org.quartz.impl.jdbcjobstore.JobStoreTX
#            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
#            tablePrefix: qrtz_
#            isClustered: true
#            useProperties: false
#            txIsolationLevelSerializable: false
#            misfireThreshold: 5000
#            clusterCheckinInterval: 10000
server:
  port: 8080
  servlet:
    context-path: /
  undertow:
    accesslog:
      enabled: true
      dir: /pp/logs/pp-test
      pattern: common
