spring:
  application:
    name: pp-auth-admin
  thymeleaf:
    mode: HTML
    encoding: utf-8
    cache: false
  datasource:
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      max-active: 20
      url: jdbc:mysql://sontion.cn:3306/pp_auth?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=PRC&useSSL=false
      username: root
      password: rootabc,123
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
  quartz:
    job-store-type: jdbc
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
            instanceName: pp_clusteredScheduler
            skipUpdateCheck: true
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: qrtz_
            isClustered: true
            useProperties: false
            txIsolationLevelSerializable: false
            misfireThreshold: 5000
            clusterCheckinInterval: 10000
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: static/i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size:  10MB
      # 设置总上传的文件大小
      max-request-size:  20MB
server:
  port: 8081
  servlet:
    context-path: /
  undertow:
    accesslog:
      enabled: true
      dir: /pp/logs/pp-admin
      pattern: common
mybatis:
  mapper-locations: classpath*:**/mapper/**/*Mapper.xml

# 项目相关配置
pp:
  common:
    # 文件路径 示例（ Windows配置D:/pp/uploadPath，Linux配置 /home/pp/uploadPath）
    profile: D:/pp/uploadPath
  log:
    open: true
    type: jdbc
